name: pytest

on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install FFmpeg
      run: |
        sudo apt-get install -y ffmpeg
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv discord.py[voice] pylint pytest
    - name: Test tunee.py functions with pytest
      run: |
        pytest -s